/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#004747",
        "surface-dim": "#d1d5d7",
        "on-primary-fixed-variant": "#60000b",
        "surface-variant": "#dadddf",
        "secondary-fixed-dim": "#7ee5e4",
        "error-dim": "#a70138",
        "primary-fixed": "#ff7671",
        "primary-dim": "#a4001a",
        "on-primary": "#ffefee",
        "outline-variant": "#abadae",
        "on-secondary-fixed-variant": "#006666",
        "surface-container-high": "#e0e3e4",
        "inverse-primary": "#ff5354",
        "secondary-fixed": "#8cf3f3",
        "outline": "#757778",
        "tertiary-dim": "#a1003f",
        "on-tertiary-container": "#670025",
        "surface-tint": "#b61424",
        "surface-bright": "#f5f6f7",
        "on-secondary-container": "#005c5c",
        "on-tertiary": "#ffefee",
        "secondary-container": "#8cf3f3",
        "on-tertiary-fixed-variant": "#77002d",
        "on-error": "#ffefef",
        "on-primary-fixed": "#000000",
        "inverse-surface": "#0c0f10",
        "error": "#b41340",
        "tertiary": "#b70049",
        "on-error-container": "#510017",
        "tertiary-container": "#ff8fa4",
        "surface": "#f5f6f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff1f2",
        "secondary": "#006666",
        "secondary-dim": "#005959",
        "inverse-on-surface": "#9b9d9e",
        "surface-container": "#e6e8ea",
        "on-background": "#2c2f30",
        "on-secondary": "#bbfffe",
        "error-container": "#f74b6d",
        "primary": "#b61424",
        "on-surface": "#2c2f30",
        "primary-container": "#ff7671",
        "on-surface-variant": "#595c5d",
        "tertiary-fixed-dim": "#ff7794",
        "primary-fixed-dim": "#ff5a59",
        "tertiary-fixed": "#ff8fa4",
        "on-tertiary-fixed": "#390011",
        "background": "#f5f6f7",
        "surface-container-highest": "#dadddf",
        "on-primary-container": "#4e0007"
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      backgroundImage: {
        "gradient-curator": "linear-gradient(135deg, #b61424 0%, #ff7671 100%)",
        "gradient-secondary": "linear-gradient(135deg, #006666 0%, #7ee5e4 100%)",
      },
    },
  },
  plugins: [],
};
